### ISSUE TITLE
Error opening ipynb file

### ISSUE THREAD

**Issue by Manny5Parkinson** [ratulKabir/Custom-Object-Detection-using-Darkflow#1]
Hi,
Great Tutorial there but you python notebook doesn't seem to open. I even downloaded the entire zip and tried opening it, but the error persists.
Please look into it

**Comment by ratulKabir** [comment]
Hi,
Thanks for detecting the issue. I have tried re-uploading the file. Looks like it isn't working. Just email me and I will send you the file.

**Comment by Manny5Parkinson** [comment]
Hey,
You can mail me the python notebook here.
Thank you
